// =========================================================
// MICKA OIL WEBSITE TRANSLATIONS
// ---------------------------------------------------------
// 01. Translation dictionary
// 02. Language toggle setup
// 03. DOM translation renderer
// 04. Loyalty card button labels
// =========================================================

// =========================================================
// 01. TRANSLATION DICTIONARY
// =========================================================
const translations = {
  sq: {
    // ========== NAVBAR ==========
    nav_about: "RRETH NESH",
    nav_gallery: "GALERIA",
    nav_locations: "VENDNDODHJET",
    nav_loyalty: "KARTA E BESNIKËRISË",
    nav_contact: "KONTAKTO",

    // ========== HOME HERO ==========
    home_eyebrow: "Energjia që mban Shqipërinë në lëvizje",
    home_title: "Karburant që<br><span>lëviz ritmin</span><br>e Shqipërisë.",
    home_lead: "Nga drejtuesit individualë te bizneset, flotat dhe transporti profesional, Micka Oil ofron karburant të kontrolluar dhe shërbim të besueshëm në pikat kyçe të vendit.",
    home_cta_contact: "Kërko ofertë",
    home_cta_locations: "Gjej stacionin më të afërt",
    home_metric_stations: "Pika aktive",
    home_metric_experience: "Vite eksperiencë",
    home_metric_supply: "Shërbim në pika kyçe",
    home_metric_quality: "Cilësi & kontroll",
    home_card_label: "Zgjidhje për biznesin",
    home_card_title: "Partner energjie për kompani, flota dhe transport",
    home_card_text: "Kontrata furnizimi, shpërndarje e planifikuar dhe mbështetje profesionale për operim të sigurt e pa ndërprerje.",
    home_mini1_title: "Karburant i certifikuar",
    home_mini1_text: "Cilësi e verifikuar për automjete, biznese dhe përdorim profesional.",
    home_mini2_title: "Shërbim me ritëm",
    home_mini2_text: "Rrjet pikash dhe operim i shpejtë për furnizim pa vonesa të panevojshme.",
    home_showcase_kicker: "Në terren",
    home_showcase_title: "Pamje nga rrjeti Micka Oil",
    home_showcase_text: "Nga stacionet tona te operimi ditor, kjo pjesë prezanton infrastrukturën, standardin e shërbimit dhe praninë vizuale të Micka Oil në terren.",
    home_highlight1: "24/7 në pika kyçe",
    home_highlight2: "Mbështetje për flota dhe biznese",
    home_highlight3: "Rrjet në qytete strategjike",
    home_locations_kicker: "Rrjeti ynë",
    home_locations_title: "Na gjeni në hartë",
    home_locations_text: "Shihni ku operojmë dhe kaloni te faqja e vendndodhjeve për oraret, shërbimet dhe udhëzimet e plota.",
    home_prices_kicker: "Çmimet referente",
    home_prices_brandline: "ENERGJI PËR ÇDO RRUGË",
    home_prices_title: "Çmimet e sotme",
    home_prices_text: "Çmimet referente për pikën kryesore në Tiranë. Pikat e tjera mund të kenë ndryshime të vogla sipas vendndodhjes.",
    home_prices_station_label: "Pika kryesore",
    home_prices_station_value: "Tiranë",
    home_prices_updated_label: "Përditësuar",
    home_prices_updated_value: "25/05/2026",
    home_prices_exchange_label: "Kursi i këmbimit",
    home_prices_note: "Çmimet në stacionet e tjera mund të ndryshojnë. Për furnizime me volum ose kontrata biznesi, na kontaktoni direkt.",
    home_prices_calculator_title: "Llogarit koston",
    home_prices_calculator_text: "Zgjidh karburantin dhe shiko koston e përafërt për furnizimin tënd.",
    home_prices_quantity_label: "Sasia (Litra)",
    home_prices_selected_label: "Përzgjedhur",
    home_prices_estimate_label: "Kosto e përafërt",
    home_prices_unit: "Litra",
    home_prices_fleet_eyebrow: "Keni flotë?",
    home_prices_fleet_title: "Kërko ofertë për flotë",
    home_prices_fleet_text: "Zgjidhje të personalizuara dhe çmime speciale për furnizime me volum.",
    home_prices_fleet_cta: "Na kontakto",
    home_prices_quality_note: "Cilësi dhe saktësi në çdo litër.",
    home_proof_kicker: "Çfarë vlerësojnë klientët",
    home_proof_title: "Besimi që vazhdon çdo ditë",
    home_proof_1_title: "Shërbim 24/7",
    home_proof_1_text: "Stacione në pika kyçe dhe shërbim 24/7 për furnizim pa ndërprerje.",
    home_proof_2_title: "Kontroll cilësie",
    home_proof_2_text: "Produkte të kontrolluara dhe të përshtatshme për përdorim personal e profesional.",
    home_proof_3_title: "Zgjidhje për biznese",
    home_proof_3_text: "Mbështetje për flota, kompani dhe operim me volum në disa qytete.",
    home_proof_4_title: "Rrjet i afërt",
    home_proof_4_text: "Prani në zona strategjike për furnizim më të shpejtë dhe më të afërt.",
    home_business_kicker: "Për biznese",
    home_business_title: "Furnizim i organizuar për kompani, flota dhe transport",
    home_business_text: "Nëse menaxhoni automjete, transport, projekte apo furnizime me volum, Micka Oil mund të strukturojë një zgjidhje të përshtatur për ritmin e punës suaj.",
    home_business_point_1: "Kontrata furnizimi dhe çmime të strukturuara",
    home_business_point_2: "Mbështetje për flota, transport dhe operim ditor",
    home_business_point_3: "Kontakt i drejtpërdrejtë për kërkesa me volum",
    home_business_cta_primary: "Kërko ofertë biznesi",
    home_business_cta_secondary: "Telefono tani",
    home_locations_cta: "Shiko të gjitha vendndodhjet",

    // ========== SEO ==========
    meta_home_title: "Micka Oil | Karburant cilësor dhe shërbime energjie",
    meta_home_description: "Micka Oil ofron karburant cilësor, furnizim për biznese, shërbime për flota dhe pika karburanti në qytete kryesore të Shqipërisë.",
    meta_about_title: "Rreth Nesh | Micka Oil",
    meta_about_description: "Njihuni me historinë, misionin, vlerat dhe rrjetin e Micka Oil, partneri juaj i besuar për furnizim me karburant në Shqipëri.",
    meta_gallery_title: "Galeria | Micka Oil",
    meta_gallery_description: "Shikoni galerinë e Micka Oil me pika karburanti, shërbime, transport dhe kartat tona të besnikërisë.",
    meta_locations_title: "Vendndodhjet | Micka Oil",
    meta_locations_description: "Gjeni pikën më të afërt Micka Oil, shikoni shërbimet e disponueshme dhe merrni udhëzime të shpejta në hartë.",
    meta_contact_title: "Kontakt | Micka Oil",
    meta_contact_description: "Kontaktoni Micka Oil për furnizim me karburant, bashkëpunime biznesi, karta besnikërie dhe informacione mbi pikat tona.",
    meta_loyalty_title: "Karta e Besnikërisë | Micka Oil",
    meta_loyalty_description: "Zbuloni kartën e besnikërisë, kartën VIP dhe zgjidhjet për bizneset e Micka Oil me përfitime dhe fleksibilitet më të madh.",
    meta_thankyou_title: "Faleminderit | Micka Oil",
    meta_thankyou_description: "Faleminderit që kontaktuat Micka Oil. Mesazhi juaj u dërgua me sukses.",
    
    // ========== INDEX PAGE - ABOUT SECTION ==========
    about_kicker: "Rreth nesh",
    about_title: "Rreth Micka Oil",
    about_text: "Micka Oil është një kompani shqiptare e specializuar në furnizimin me karburant cilësor për automjete, biznese, transport dhe industri. Me 25 vite eksperiencë në treg dhe një rrjet pikash të pozicionuara në qytete kyçe të Shqipërisë, ne garantojmë furnizim të shpejtë, të sigurt dhe të besueshëm. Çdo produkt që ofrojmë është i kontrolluar dhe i certifikuar sipas standardeve më të larta, për të siguruar performancë, efikasitet dhe qetësi për çdo klient. Misioni ynë është të ofrojmë energji që mban në lëvizje ekonominë shqiptare me profesionalizëm, integritet dhe shërbim afatgjatë. Micka Oil është partneri juaj i besuar për furnizime të qëndrueshme dhe mbështetje reale në terren.",
    
    // ========== INDEX PAGE - SERVICES SECTION ==========
    services_kicker: "Çfarë ofrojmë",
    services_title: "Shërbime",
    services_subtitle: "Zgjidhje të strukturuara për individë, biznese, flota dhe transport profesional.",
    service1_title: "Karburant premium për automjete",
    service1_desc: "Karburant i certifikuar për performancë të lartë, konsum më efikas dhe mbrojtje të motorit.",
    service2_title: "Transport i lëndëve hidrokarbure",
    service2_desc: "Transport i sigurt dhe profesional i lëndëve hidrokarbure për furnizim të pandërprerë.",
    service3_title: "Furnizim për mjete lundruese dhe porte",
    service3_desc: "Zgjidhje profesionale për furnizim të sigurt në porte, marina dhe pika operimi detar.",
    service4_title: "Import dhe eksport karburanti",
    service4_desc: "Menaxhim i koordinuar i importit, logjistikës dhe shpërndarjes për furnizim të qëndrueshëm.",
    service5_title: "Furnizim helikopterash dhe aviacion",
    service5_desc: "Karburant dhe mbështetje furnizimi për operime ajrore, helikopterë dhe shërbime aviacioni.",
    service_cta: "Kërko informacion",
    
    // ========== INDEX PAGE - PRODUCTS SECTION ==========
    products_kicker: "Karburantet tona",
    products_title: "Produkte",
    products_subtitle: "Karburante të certifikuara për performancë dhe përdorim të sigurt.",
    products_group1_kicker: "Për automjete",
    products_group1_title: "Karburante për përdorim të përditshëm<span> dhe performancë</span>",
    products_group1_text: "Produkte të përzgjedhura për drejtim të sigurt, efikasitet dhe mbrojtje të motorit në çdo kilometër.",
    products_group2_kicker: "Për industri",
    products_group2_title: "Produkte për infrastrukturë dhe procese industriale",
    products_group2_text: "Zgjidhje të dedikuara për projekte me volum, furnizim teknik dhe kërkesa të qëndrueshme energjie.",
    products_group3_kicker: "Produkte speciale",
    products_group3_title: "Furnizim i specializuar për operime specifike",
    products_group3_text: "Zgjidhje të dedikuara për sektorë që kërkojnë standard të lartë, siguri dhe performancë të kontrolluar.",
    products_cta_text: "Keni nevojë për furnizim të personalizuar apo ofertë sipas volumit?",
    products_cta_button: "Kërko ofertë",
    product1_name: "Benzinë",
    product1_badge: "100 OKTAN",
    product1_desc: "Zgjedhje premium për performancë më të lartë dhe reagim më të mirë të motorit.",
    product1_tag1: "Premium",
    product1_tag2: "Performancë",
    product1_tag3: "Pastrues",
    product2_name: "Benzinë",
    product2_badge: "95 OKTAN",
    product2_desc: "Zgjedhje e balancuar për përdorim të përditshëm, e qëndrueshme dhe efikase.",
    product2_tag1: "Standard",
    product2_tag2: "Efiçencë",
    product2_tag3: "E përditshme",
    product3_name: "Extra Diesel Shell",
    product3_badge: "DIESEL",
    product3_desc: "Për flota dhe udhëtime të gjata, me fokus në pastërti dhe punë të qëndrueshme.",
    product3_tag1: "Flota",
    product3_tag2: "Udhëtime",
    product3_tag3: "Stabil",
    product4_name: "Naftë",
    product4_badge: "10 PPM",
    product4_desc: "Standard modern për emetime më të ulëta dhe kompatibilitet më të mirë me motorë të rinj.",
    product4_tag1: "10ppm",
    product4_tag2: "Euro",
    product4_tag3: "Më pastër",
    product5_name: "Auto Gas",
    product5_badge: "LPG",
    product5_desc: "Zgjedhje ekonomike dhe praktike për përdorim të përditshëm me mirëmbajtje të rregullt.",
    product5_tag1: "Ekonomik",
    product5_tag2: "Praktik",
    product5_tag3: "I qëndrueshëm",
    product6_name: "Furnizim\nme Bitum",
    product6_badge: "BITUM",
    product6_desc: "Zgjidhje profesionale për projekte infrastrukturore, ndërtim rrugësh dhe furnizim industrial.",
    product6_tag1: "Infrastrukturë",
    product6_tag2: "Industrial",
    product6_tag3: "Furnizim",
    product7_name: "Jet A1",
    product7_badge: "AVIATION",
    product7_desc: "Karburant aviacioni me standard të lartë për operim të sigurt dhe performancë të qëndrueshme.",
    product7_tag1: "Aviacion",
    product7_tag2: "Standard",
    product7_tag3: "Siguri",
    product8_name: "Mazut",
    product8_badge: "FUEL OIL",
    product8_desc: "Zgjidhje energjie për procese industriale dhe nevoja me konsum të lartë e të qëndrueshëm.",
    product8_tag1: "Industri",
    product8_tag2: "Energji",
    product8_tag3: "Kapacitet",
    
    // ========== INDEX PAGE - LOCATIONS ==========
    locations_title: "Vendndodhjet",
    
    // ========== CONTACT PAGE ==========
    contact_title: "Na Kontaktoni",
    contact_subtitle: "Na dërgoni një mesazh dhe ne do t'ju kontaktojmë sa më shpejt.",
    form_firstname: "Emri",
    form_lastname: "Mbiemri",
    form_email: "Email",
    form_phone: "Numri i telefonit",
    form_message: "Mesazhi",
    form_submit: "Dërgo",
    contact_official: "Forma zyrtare është mënyra më e mirë për kontakt.",
    contact_prefer: "Nëse preferoni, mund të na kontaktoni edhe drejtpërdrejt:",
    contact_overlay_kicker: "MICKA OIL",
    contact_overlay_title: "Flisni me ekipin tonë",
    contact_overlay_text: "Për bashkëpunime, furnizim, karta besnikërie ose pyetje për pikat tona, jemi gati t'ju ndihmojmë.",
    contact_action_phone: "Telefono",
    contact_action_whatsapp: "WhatsApp",
    contact_action_email: "Email",
    contact_point_business_title: "Biznes",
    contact_point_business_text: "Furnizim për kompani, flota dhe kërkesa me volum.",
    contact_point_support_title: "Mbështetje",
    contact_point_support_text: "Përgjigje të shpejta për karta, stacione dhe shërbim në terren.",
    contact_form_title: "Na shkruani sot.",
    contact_form_text: "Plotësoni formularin dhe ekipi ynë do t'ju kontaktojë sa më shpejt.",
    
    // ========== GALLERY PAGE ==========
    gallery_title: "Galeria",
    gallery_subtitle: "Pamje nga pikat tona të karburantit, shërbimi dhe infrastruktura Micka Oil.",
    gallery_breadcrumb: "Galeria",
    gallery_header_title: "Media <em>&amp; Galeria</em>",
    gallery_header_desc: "Pamje nga pikat, shërbimet dhe infrastruktura Micka Oil në të gjithë Shqipërinë.",
    gallery_chip_stations: "Stacione",
    gallery_chip_service: "Shërbim",
    gallery_chip_infrastructure: "Infrastrukturë",
    gallery_hive_kicker: "Më shumë nga rrjeti",
    gallery_hive_title: "Më shumë pamje nga Micka Oil",
    gallery_hive_text: "Një përzgjedhje më e gjerë nga pikat tona, infrastruktura dhe prania e markës në terren.",
    
    // ========== LOCATION PAGE ==========
    location_hero_title: "Vendndodhjet Tona",
    location_hero_subtitle: "Gjeni pikën Micka Oil më të afërt me ju dhe merrni drejtimet menjëherë.",
    location_cards_kicker: "Pikat tona",
    location_cards_title: "Pikat Tona",
    location_footer_stations: "Google Maps",
    location_view_map: "Shiko Hartën",
    location_directions: "Udhëzime",
    location_services_label: "Shërbime",
    
    // ========== ABOUT PAGE (RRETH-NESH) ==========
    about_hero_text: "Energji që lëviz besimin.\nCilësi që ndërton marrëdhënie afatgjata.",
    about_who_title: "Kush Jemi Ne",
    about_who_p1: "Micka Oil është një kompani shqiptare e specializuar në furnizimin me karburant të standardeve të larta për individë, biznese dhe industri. Me mbi 20 vite eksperiencë në treg, ne kemi ndërtuar një emër të bazuar në besueshmëri, cilësi dhe korrektësi.",
    about_who_p2: "Rrjeti ynë i pikave shtrihet në qytete strategjike të Shqipërisë, duke siguruar akses të shpejtë dhe shërbim të qëndrueshëm për çdo klient. Çdo litër karburanti që ofrojmë kalon nëpër procese të rrepta kontrolli, në përputhje me standardet kombëtare dhe ndërkombëtare.",
    about_who_p3: "Për ne, karburanti nuk është thjesht produkt — është përgjegjësi. Përgjegjësi ndaj klientëve tanë, partnerëve tanë dhe mjedisit ku operojmë.",
    about_page_kicker: "Rreth nesh",
    about_page_title: "<span>Energjia lokale që mban</span><span>Shqipërinë në lëvizje.</span>",
    about_page_lead: "Micka Oil ndërton furnizim të besueshëm për drejtues, familje, flota dhe biznese që kërkojnë standard, ritëm dhe korrektësi afatgjatë.",
    about_page_cta_primary: "Na kontaktoni",
    about_page_cta_secondary: "Shiko rrjetin tonë",
    about_page_badge_label: "Në terren çdo ditë",
    about_page_badge_title: "Furnizim i qëndrueshëm, shërbim me standard.",
    about_page_badge_text: "Nga pikat urbane te furnizimi për flota, ne ruajmë të njëjtin fokus: cilësi të kontrolluar dhe reagim të shpejtë.",
    about_metric_availability: "Shërbim në pika kyçe",
    about_metric_business: "Mbështetje për flota dhe biznese",
    about_story_kicker: "Historia jonë",
    about_story_title: "Micka Oil u ndërtua mbi korrektësi, jo vetëm mbi volum.",
    about_story_p1: "Që në fillim, synimi ynë ka qenë i qartë: të ndërtojmë një rrjet furnizimi me disiplinë, transparencë dhe respekt për klientin. Për ne, karburanti është pjesë e ritmit të përditshëm të njerëzve dhe bizneseve që na besojnë.",
    about_story_p2: "Micka Oil është rritur duke investuar në pika strategjike, kontroll cilësie dhe shërbim praktik për rrugën shqiptare. Kjo na ka bërë partner të dobishëm si për drejtues individualë, ashtu edhe për kompani, transport dhe flota.",
    about_manifesto_label: "Për ne",
    about_manifesto_text: "Karburanti nuk është thjesht produkt. Është përgjegjësi ndaj klientëve, partnerëve dhe çdo rruge ku lëviz marka jonë.",
    about_network_label: "Rrjet në terren",
    about_network_text: "Prani aktive në Tiranë, Kavajë, Memaliaj, Patos, Gjirokastër dhe Prush, me fokus në akses të shpejtë dhe mbulim të zonave kyçe.",
    about_pillars_kicker: "Pse na zgjedhin",
    about_pillars_title: "Çfarë i mban klientët afër Micka Oil",
    about_pillars_text: "Besimi ndërtohet nga mënyra si operon një kompani çdo ditë. Këto janë arsyet që klientët tanë ndiejnë në terren.",
    about_pillar1_title: "Cilësi e kontrolluar",
    about_pillar1_text: "Produkte të monitoruara dhe standard i qëndrueshëm në çdo pikë furnizimi.",
    about_pillar2_title: "Rrjet në pika kyçe",
    about_pillar2_text: "Prani në qytete dhe akse që mbajnë lëvizjen e përditshme të klientëve tanë.",
    about_pillar3_title: "Zgjidhje për biznese",
    about_pillar3_text: "Mbështetje për kompani, flota dhe furnizime me volum sipas nevojës reale.",
    about_pillar4_title: "Shërbim i vazhdueshëm",
    about_pillar4_text: "Ritëm operimi i qëndrueshëm, reagim i shpejtë dhe fokus te marrëdhënia afatgjatë.",
    about_journey_kicker: "Rrugëtimi dhe rritja",
    about_journey_title: "Nga një bazë lokale në një rrjet që mbulon pika kyçe",
    about_journey_text: "Rritja jonë ka ardhur me zgjerim të kujdesshëm, investim në standard dhe afrim me nevojat reale të tregut shqiptar.",
    about_journey_2003_title: "Fillimi i markës",
    about_journey_2003_text: "Hapat e parë të Micka Oil me fokus te furnizimi lokal dhe marrëdhënia e besimit me klientin.",
    about_journey_2008_title: "Zgjerimi i rrjetit",
    about_journey_2008_text: "Rritje e pranisë në qytete strategjike dhe forcim i infrastrukturës së furnizimit.",
    about_journey_2015_title: "Hyrja në furnizim biznesi",
    about_journey_2015_text: "Zgjidhje të dedikuara për biznese, transport dhe flota me kërkesa më të mëdha operacionale.",
    about_journey_2020_title: "Modernizimi i shërbimit",
    about_journey_today_title: "Partner energjie në terren",
    about_journey_today_text: "Një rrjet aktiv që kombinon cilësinë e produktit me ritëm, afërsi dhe mbështetje të vazhdueshme.",
    about_cta_kicker: "Bashkëpunim",
    about_cta_title: "Gati për furnizim më të qëndrueshëm?",
    about_cta_text: "Kontaktoni ekipin tonë për bashkëpunime, furnizim biznesi dhe zgjidhje afatgjata që ecin me ritmin tuaj.",
    about_cta_button: "Na kontaktoni",
    stats_years: "Vite Eksperiencë",
    stats_stations: "Pika Karburanti",
    stats_customers: "Klientë të Kënaqur",
    stats_cities: "Qytete në Shqipëri",
    mission_title: "Misioni Ynë",
    mission_text: "Të ofrojmë furnizim të sigurt, cilësor dhe të qëndrueshëm me karburant, duke ndërtuar marrëdhënie afatgjata me klientët dhe partnerët tanë.",
    vision_title: "Vizioni Ynë",
    vision_text: "Të jemi një nga kompanitë më të besuara të energjisë në Shqipëri, duke u zgjeruar vazhdimisht dhe duke investuar në cilësi, teknologji dhe njerëz.",
    values_title: "Vlerat Tona",
    value1_title: "Cilësia",
    value1_desc: "— çdo produkt i testuar dhe i certifikuar",
    value2_title: "Besueshmëria",
    value2_desc: "— korrektësi në çdo bashkëpunim",
    value3_title: "Transparenca",
    value3_desc: "— komunikim i hapur dhe i ndershëm",
    value4_title: "Partneriteti",
    value4_desc: "— rritemi së bashku me klientët tanë",
    value5_title: "Përgjegjësia",
    value5_desc: "— ndaj mjedisit dhe komunitetit",
    partners_title: "Partnerët Tanë",
    partners_text: "Micka Oil bashkëpunon me furnizues dhe partnerë të besueshëm për të garantuar cilësi konstante dhe standarde të larta shërbimi.",
    partner1: "Furnizues Karburanti",
    partner2: "Biznese & Flota",
    partner3: "Transport & Logjistikë",
    partner4: "Institucione & Projekte",
    timeline_title: "Rrugëtimi Ynë",
    timeline_2003: "Themelimi i Micka Oil me fokus në furnizim lokal dhe shërbim të besueshëm.",
    timeline_2008: "Zgjerimi i rrjetit të pikave të karburantit dhe investime në cilësi.",
    timeline_2015: "Fillimi i bashkëpunimeve me biznese, flota dhe industri të ndryshme.",
    timeline_2020: "Modernizimi i shërbimeve dhe standardizimi sipas praktikave evropiane.",
    timeline_today_year: "SOT",
    timeline_today: "Micka Oil operon në disa qytete të Shqipërisë si partner energjie i besuar.",
    cta_title: "Pse Micka Oil?",
    cta_text: "Sepse ne nuk shesim vetëm karburant — ne ndërtojmë besim.",
    cta_button: "Na Kontaktoni",
    
    // ========== LOYALTY CARDS PAGE ==========
    loyalty_hero_title: "KARTA E BESNIKËRISË",
    loyalty_card1_title: "Karta e Besnikërisë",
    loyalty_card1_desc: "Për përdorim personal dhe mbledhje përfitimesh.",
    loyalty_card1_benefit1: "Përdorim personal",
    loyalty_card1_benefit2: "Aplikimi bëhet te pika",
    loyalty_card1_benefit3: "Përfiton 5 lekë më poshtë çmimit të tabelës",
    loyalty_card1_benefit4: "Specifike për një makinë",
    loyalty_card1_note: "ℹ️ Karta aktivizohet menjëherë në pikën e furnizimit.",
    loyalty_card2_title: "Karta VIP",
    loyalty_card2_desc: "Zbritje dhe përfitime ekskluzive.",
    loyalty_card2_benefit1: "Aplikimi vlen për produkte specifike që tregtojmë",
    loyalty_card2_benefit2: "Përdorimi është personal dhe realizohet me parapagim",
    loyalty_card2_benefit3: "Furnizimi ofrohet për çdo mjet që përdor të njëjtin produkt",
    loyalty_card2_benefit4: "Sasia minimale për t'u kualifikuar është 1000 litra",
    loyalty_card2_benefit5: "Kushtet dhe uljet përcaktohen në varësi të kërkesës",
    loyalty_card2_benefit6: "Për detaje shtesë, kontaktoni agjentin tonë",
    loyalty_card2_note: "ℹ️ Përfitimet VIP aktivizohen sipas marrëveshjes me Micka Oil.",
    loyalty_card3_title: "Karta Tollon",
    loyalty_card3_desc: "Zgjidhje për biznese dhe flotë.",
    loyalty_card3_benefit1: "Tollon elektronik me parapagim ose prapapagim",
    loyalty_card3_benefit2: "I dedikuar për biznese dhe firma",
    loyalty_card3_benefit3: "I vlefshëm për çdo mjet të regjistruar",
    loyalty_card3_benefit4: "Zbritjet varen nga konsumi dhe kërkesa",
    loyalty_card3_benefit5: "Për më shumë informacion, kontaktoni agjentin tonë",
    loyalty_card3_note: "ℹ️ Fleksibilitet maksimal për menaxhimin e flotës.",
    loyalty_btn_view: "Shiko Përfitimet",
    loyalty_btn_close: "Mbyll Përfitimet",
    loyalty_support_title: "Keni nevojë për ndihmë me kartën e besnikërisë?",
    loyalty_support_text: "Na kontaktoni për regjistrim, pikë, balancë, aktivizim ose mbështetje për llogarinë tuaj.",
    loyalty_support_button: "Pyet për kartën",
    loyalty_support_meta1: "Për asistencë në pikë ose pyetje urgjente, ekipi ynë është i gatshëm 24/7.",
    loyalty_support_meta2: "Faleminderit që zgjidhni Micka Oil. Ne mbajmë në lëvizje rrugëtimin tuaj.",
    loyalty_page_title: "Më shumë se një kartë<br><span>besnikëria që shpërblehet.</span>",
    loyalty_page_lead1: "Zgjidh kartën që i përshtatet nevojave të tua.",
    loyalty_page_lead2: "Përfito më shumë në çdo furnizim me Micka Oil.",
    loyalty_page_apply: "Apliko tani",
    loyalty_page_how: "Si funksionon",
    loyalty_compare_title: "Krahaso përfitimet",
    loyalty_plan_standard: "Standart",
    loyalty_plan_vip: "VIP",
    loyalty_plan_business: "Business",
    loyalty_benefit_label: "Përfitimi",
    loyalty_benefit_use: "Përdorim",
    loyalty_benefit_fuel: "Zbritje në karburant",
    loyalty_benefit_offers: "Oferta dhe promovime ekskluzive",
    loyalty_benefit_points: "Grumbullim pikësh bonus",
    loyalty_benefit_priority: "Prioritet në shërbim",
    loyalty_benefit_fleet: "Menaxhim i flotës së automjeteve",
    loyalty_benefit_reports: "Raporte mujore të konsumit",
    loyalty_benefit_invoice: "Pagesa me faturë",
    loyalty_benefit_support: "Mbështetje e dedikuar",
    loyalty_value_2lek: "2 Lekë/L",
    loyalty_value_5lek: "5 Lekë/L",
    loyalty_value_7lek: "7 Lekë/L",
    loyalty_value_personal: "Personal",
    loyalty_value_business_use: "Biznes",
    loyalty_steps_title: "Si funksionon?",
    loyalty_step1_title: "Apliko",
    loyalty_step1_text: "Plotëso formularin online ose në pikat tona.",
    loyalty_step2_title: "Merr kartën",
    loyalty_step2_text: "Merr kartën tënde fizike ose në format digital.",
    loyalty_step3_title: "Furnizo dhe përfito",
    loyalty_step3_text: "Furnizo në pikat Micka Oil dhe përfito çdo ditë.",
    loyalty_reasons_title: "Pse të zgjidhni kartën e besnikërisë Micka Oil?",
    loyalty_reason1: "Regjistrim i shpejtë<br>Apliko lehtë online ose në pikë.",
    loyalty_reason2: "E vlefshme në të gjithë rrjetin tonë të pikave.",
    loyalty_reason3: "Oferta dhe zbritje ekskluzive gjatë gjithë vitit.",
    loyalty_reason4: "Suport i dedikuar për çdo pyetje dhe kërkesë.",
    loyalty_faq_title: "Pyetjet më të shpeshta",
    loyalty_faq1_q: "Ku mund ta përdor kartën e besnikërisë?",
    loyalty_faq1_a: "Kartën e besnikërisë Micka Oil mund ta përdorni në të gjitha pikat tona pjesëmarrëse. Mjafton ta paraqisni gjatë furnizimit për të përfituar nga programi i besnikërisë.",
    loyalty_faq2_q: "Si grumbullohen pikët e besnikërisë?",
    loyalty_faq2_a: "Sa herë që furnizoni në Micka Oil, grumbulloni pikë besnikërie bazuar në vlerën e blerjes suaj. Pikët regjistrohen automatikisht në kartën tuaj dhe mund të përdoren për përfitime të ndryshme.",
    loyalty_faq3_q: "A ka kosto pajisja me kartën?",
    loyalty_faq3_a: "Jo. Aplikimi dhe pajisja me kartën e besnikërisë janë plotësisht pa pagesë për të gjithë klientët tanë.",
    loyalty_faq4_q: "Çfarë ndodh nëse humbas kartën?",
    loyalty_faq4_a: "Në rast humbjeje, kontaktoni stafin në pikën më të afërt Micka Oil. Karta mund të çaktivizohet dhe përfitimet e grumbulluara mund të transferohen në një kartë të re.",
    loyalty_cta_title: "Gati për të përfituar?",
    loyalty_cta_text: "Bëhu pjesë e mijëra drejtuesve që zgjedhin Micka Oil çdo ditë.",
    
    // ========== FOOTER ==========
    footer_brand_text: "Karburant cilësor, shërbim i besueshëm dhe mbështetje profesionale në çdo pikë.",
    footer_menu: "Menu",
    footer_about: "Rreth Nesh",
    footer_gallery: "Galeri",
    footer_locations: "Vendndodhjet",
    footer_loyalty: "Karta e Besnikërisë",
    footer_contact: "Kontakt",
    footer_contact_title: "Kontakt",
    footer_follow: "Na Ndiqni",
    footer_rights: "Të gjitha të drejtat e rezervuara.",

    // ========== THANK YOU PAGE ==========
    thankyou_brand_tag: "Furnizim i besueshëm",
    thankyou_side_title: "Kërkesa u regjistrua.",
    thankyou_side_text: "Mesazhi juaj është pranuar nga sistemi ynë dhe do të shqyrtohet nga ekipi përkatës.",
    thankyou_status_received: "Mesazh i pranuar",
    thankyou_status_followup: "Ndjekje nga ekipi",
    thankyou_kicker: "Faleminderit",
    thankyou_title: "Kërkesa juaj u dërgua me sukses.",
    thankyou_text: "Faleminderit që kontaktuat Micka Oil. Ekipi ynë do të shqyrtojë detajet e dërguara dhe do t'ju kontaktojë sa më shpejt për hapat e mëtejshëm.",
    thankyou_step1_title: "Shqyrtim i kërkesës",
    thankyou_step1_text: "Informacioni i dërguar do të verifikohet nga ekipi përkatës.",
    thankyou_step2_title: "Kontakt i radhës",
    thankyou_step2_text: "Do t'ju kontaktojmë për përgjigje, sqarime ose bashkëpunim.",
    thankyou_home_cta: "Faqja kryesore",
    thankyou_phone_cta: "Kontakt direkt",
    thankyou_redirect: "Do të ridrejtoheni automatikisht në faqen kryesore pas 20 sekondash."
  },
  
  en: {
    // ========== NAVBAR ==========
    nav_about: "ABOUT US",
    nav_gallery: "GALLERY",
    nav_locations: "LOCATIONS",
    nav_loyalty: "LOYALTY CARD",
    nav_contact: "CONTACT",

    // ========== HOME HERO ==========
    home_eyebrow: "Energy that keeps Albania moving",
    home_title: "Fuel that<br><span>keeps the rhythm</span><br><span class=\"hero-title-dark\">of Albania moving.</span>",
    home_lead: "From individual drivers to businesses, fleets, and professional transport, Micka Oil delivers controlled fuel quality and dependable service across the stations that matter most.",
    home_cta_contact: "Request an offer",
    home_cta_locations: "Find the nearest station",
    home_metric_stations: "Active stations",
    home_metric_experience: "Years of experience",
    home_metric_supply: "Service",
    home_card_label: "Business solutions",
    home_card_title: "An energy partner for companies, fleets, and transport",
    home_card_text: "Supply contracts, planned distribution, and professional support designed for safe and uninterrupted operations.",
    home_mini1_title: "Certified fuel quality",
    home_mini1_text: "Verified quality for vehicles, businesses, and professional use.",
    home_mini2_title: "Fast-paced service",
    home_mini2_text: "A station network and responsive operation built to avoid unnecessary delays.",
    home_showcase_kicker: "On the ground",
    home_showcase_title: "A look across the Micka Oil network",
    home_showcase_text: "From our stations to daily operations, this section presents the infrastructure, service standard, and visual presence of Micka Oil on the ground.",
    home_highlight1: "24/7 in key stations",
    home_highlight2: "Support for businesses and fleets",
    home_highlight3: "Network in strategic cities",
    home_locations_kicker: "Our network",
    home_locations_title: "Find us on the map",
    home_locations_text: "See where we operate and jump to the locations page for full schedules, services, and directions.",
    home_prices_kicker: "Reference prices",
    home_prices_brandline: "ENERGY FOR EVERY ROAD",
    home_prices_title: "Today's prices",
    home_prices_text: "Reference prices for the main station in Tirana. Other stations may have small differences depending on location.",
    home_prices_station_label: "Main station",
    home_prices_station_value: "Tirana",
    home_prices_updated_label: "Updated",
    home_prices_updated_value: "25/05/2026",
    home_prices_exchange_label: "Exchange rate",
    home_prices_note: "Prices at other stations may vary. For volume supply or business contracts, contact us directly.",
    home_prices_calculator_title: "Estimate your cost",
    home_prices_calculator_text: "Pick the fuel type and see the estimated cost for your fill-up.",
    home_prices_quantity_label: "Quantity (Liters)",
    home_prices_selected_label: "Selected",
    home_prices_estimate_label: "Estimated total",
    home_prices_unit: "Liters",
    home_prices_fleet_eyebrow: "Have a fleet?",
    home_prices_fleet_title: "Request a fleet offer",
    home_prices_fleet_text: "Tailored solutions and special pricing for higher-volume supply.",
    home_prices_fleet_cta: "Contact us",
    home_prices_quality_note: "Quality and accuracy in every liter.",
    home_proof_kicker: "What clients value",
    home_proof_title: "Trust that continues every day",
    home_proof_1_title: "24/7 service",
    home_proof_1_text: "Stations in key areas and 24/7 service for uninterrupted supply.",
    home_proof_2_title: "Quality control",
    home_proof_2_text: "Controlled products suited for both personal and professional use.",
    home_proof_3_title: "Business solutions",
    home_proof_3_text: "Support for fleets, companies, and volume operations across multiple cities.",
    home_proof_4_title: "Closer network",
    home_proof_4_text: "Presence in strategic zones for faster and closer supply.",
    home_business_kicker: "For businesses",
    home_business_title: "Structured supply for companies, fleets, and transport",
    home_business_text: "If you manage vehicles, transport, projects, or high-volume supply, Micka Oil can build a solution tailored to your operating rhythm.",
    home_business_point_1: "Supply contracts and structured pricing",
    home_business_point_2: "Support for fleets, transport, and day-to-day operations",
    home_business_point_3: "Direct contact for high-volume requests",
    home_business_cta_primary: "Request a business quote",
    home_business_cta_secondary: "Call now",
    home_locations_cta: "View all locations",
    home_title: "Fuel that<br><span>keeps the rhythm</span><br><span class=\"hero-title-dark\">of Albania moving.</span>",
    home_metric_supply: "Service",
    home_metric_quality: "Quality & control",

    // ========== SEO ==========
    meta_home_title: "Micka Oil | Quality fuel and energy services",
    meta_home_description: "Micka Oil provides quality fuel, business supply, fleet services, and fuel stations across key cities in Albania.",
    meta_about_title: "About Us | Micka Oil",
    meta_about_description: "Discover Micka Oil's story, mission, values, and station network as your trusted fuel supply partner in Albania.",
    meta_gallery_title: "Gallery | Micka Oil",
    meta_gallery_description: "Explore the Micka Oil gallery with fuel stations, services, transport, and our loyalty card offers.",
    meta_locations_title: "Locations | Micka Oil",
    meta_locations_description: "Find the nearest Micka Oil station, view available services, and get fast directions on the map.",
    meta_contact_title: "Contact | Micka Oil",
    meta_contact_description: "Contact Micka Oil for fuel supply, business partnerships, loyalty cards, and information about our stations.",
    meta_loyalty_title: "Loyalty Card | Micka Oil",
    meta_loyalty_description: "Discover Micka Oil's loyalty card, VIP card, and business fleet solutions with added benefits and flexibility.",
    meta_thankyou_title: "Thank You | Micka Oil",
    meta_thankyou_description: "Thank you for contacting Micka Oil. Your message was sent successfully.",
    
    // ========== INDEX PAGE - ABOUT SECTION ==========
    about_kicker: "About us",
    about_title: "About Micka Oil",
    about_text: "Micka Oil is an Albanian company specialized in supplying quality fuel for vehicles, businesses, transport, and industry. With 25 years of market experience and a station network positioned across key Albanian cities, we guarantee fast, safe, and reliable supply. Every product we offer is controlled and certified to the highest standards in order to deliver performance, efficiency, and confidence for every customer. Our mission is to keep the Albanian economy moving through professionalism, integrity, and long-term service. Micka Oil is your trusted partner for sustainable supply and dependable support on the ground.",
    
    // ========== INDEX PAGE - SERVICES SECTION ==========
    services_kicker: "What we offer",
    services_title: "Services",
    services_subtitle: "Structured solutions for individuals, businesses, fleets, and professional transport.",
    service1_title: "Premium fuel for vehicles",
    service1_desc: "Certified fuel for strong performance, better efficiency, and engine protection.",
    service2_title: "Hydrocarbon transport",
    service2_desc: "Safe and professional hydrocarbon transport for uninterrupted supply.",
    service3_title: "Marine and port supply",
    service3_desc: "Professional solutions for safe supply in ports, marinas, and marine operations.",
    service4_title: "Fuel import and export",
    service4_desc: "Coordinated management of import, logistics, and distribution for reliable supply.",
    service5_title: "Helicopter and aviation supply",
    service5_desc: "Fuel and supply support for air operations, helicopters, and aviation services.",
    service_cta: "Request information",
    
    // ========== INDEX PAGE - PRODUCTS SECTION ==========
    products_kicker: "Our fuels",
    products_title: "Products",
    products_subtitle: "Certified fuels for performance and safe use.",
    products_group1_kicker: "For vehicles",
    products_group1_title: "Fuels for daily use<span> and performance</span>",
    products_group1_text: "Selected products for safe driving, efficiency, and engine protection on every kilometer.",
    products_group2_kicker: "For industry",
    products_group2_title: "Products for infrastructure and industrial processes",
    products_group2_text: "Dedicated solutions for volume-based projects, technical supply, and stable energy demand.",
    products_group3_kicker: "Special products",
    products_group3_title: "Specialized supply for specific operations",
    products_group3_text: "Dedicated solutions for sectors that require high standards, safety, and controlled performance.",
    products_cta_text: "Need custom supply or a quote based on volume?",
    products_cta_button: "Request an offer",
    product1_name: "Gasoline",
    product1_badge: "100 OCTANE",
    product1_desc: "Premium choice for higher performance and better engine response.",
    product1_tag1: "Premium",
    product1_tag2: "Performance",
    product1_tag3: "Cleaner",
    product2_name: "Gasoline",
    product2_badge: "95 OCTANE",
    product2_desc: "Balanced choice for daily use, stable and efficient.",
    product2_tag1: "Standard",
    product2_tag2: "Efficiency",
    product2_tag3: "Daily",
    product3_name: "Extra Diesel Shell",
    product3_badge: "DIESEL",
    product3_desc: "For fleets and long trips, focused on cleanliness and stable operation.",
    product3_tag1: "Fleet",
    product3_tag2: "Travel",
    product3_tag3: "Stable",
    product4_name: "Diesel",
    product4_badge: "10 PPM",
    product4_desc: "Modern standard for lower emissions and better compatibility with new engines.",
    product4_tag1: "10ppm",
    product4_tag2: "Euro",
    product4_tag3: "Cleaner",
    product5_name: "Auto Gas",
    product5_badge: "LPG",
    product5_desc: "Economical and practical choice for daily use with regular maintenance.",
    product5_tag1: "Economic",
    product5_tag2: "Practical",
    product5_tag3: "Sustainable",
    product6_name: "Bitumen\nSupply",
    product6_badge: "BITUMEN",
    product6_desc: "Professional solution for infrastructure projects, road construction, and industrial supply.",
    product6_tag1: "Infrastructure",
    product6_tag2: "Industrial",
    product6_tag3: "Supply",
    product7_name: "Jet A1",
    product7_badge: "AVIATION",
    product7_desc: "High-standard aviation fuel for safe operations and consistent performance.",
    product7_tag1: "Aviation",
    product7_tag2: "Standard",
    product7_tag3: "Safety",
    product8_name: "Mazut",
    product8_badge: "FUEL OIL",
    product8_desc: "Energy solution for industrial processes and high, consistent consumption needs.",
    product8_tag1: "Industry",
    product8_tag2: "Energy",
    product8_tag3: "Capacity",
    
    // ========== INDEX PAGE - LOCATIONS ==========
    locations_title: "Locations",
    
    // ========== CONTACT PAGE ==========
    contact_title: "Contact Us",
    contact_subtitle: "Send us a message and we will contact you as soon as possible.",
    form_firstname: "First Name",
    form_lastname: "Last Name",
    form_email: "Email",
    form_phone: "Phone Number",
    form_message: "Message",
    form_submit: "Send",
    contact_official: "The official form is the best way to contact us.",
    contact_prefer: "If you prefer, you can also contact us directly:",
    contact_overlay_kicker: "MICKA OIL",
    contact_overlay_title: "Talk to our team",
    contact_overlay_text: "For partnerships, fuel supply, loyalty cards, or station questions, our team is ready to help.",
    contact_action_phone: "Call",
    contact_action_whatsapp: "WhatsApp",
    contact_action_email: "Email",
    contact_point_business_title: "Business",
    contact_point_business_text: "Supply for companies, fleets, and volume-based requests.",
    contact_point_support_title: "Support",
    contact_point_support_text: "Fast answers for cards, stations, and on-the-ground service.",
    contact_form_title: "Send us a message.",
    contact_form_text: "Fill out the form and our team will get back to you as soon as possible.",
    
    // ========== GALLERY PAGE ==========
    gallery_title: "Gallery",
    gallery_subtitle: "Views from our fuel stations, service and Micka Oil infrastructure.",
    gallery_breadcrumb: "Gallery",
    gallery_header_title: "Media <em>&amp; Gallery</em>",
    gallery_header_desc: "Views from Micka Oil stations, services, and infrastructure across Albania.",
    gallery_chip_stations: "Stations",
    gallery_chip_service: "Service",
    gallery_chip_infrastructure: "Infrastructure",
    gallery_hive_kicker: "More from the network",
    gallery_hive_title: "More views from Micka Oil",
    gallery_hive_text: "A broader selection from our stations, infrastructure, and brand presence on the ground.",
    
    // ========== LOCATION PAGE ==========
    location_hero_title: "Our Locations",
    location_hero_subtitle: "Find the nearest Micka Oil station and get directions immediately.",
    location_cards_kicker: "Our stations",
    location_cards_title: "Our Stations",
    location_footer_stations: "Google Maps",
    location_view_map: "View on Map",
    location_directions: "Directions",
    location_services_label: "Services",
    
    // ========== ABOUT PAGE (RRETH-NESH) ==========
    about_hero_text: "Energy that moves trust.\nQuality that builds lasting relationships.",
    about_who_title: "Who We Are",
    about_who_p1: "Micka Oil is an Albanian company specialized in supplying high-standard fuel for individuals, businesses, and industries. With over 25 years of market experience, we have built a reputation based on reliability, quality, and integrity.",
    about_who_p2: "Our network of stations extends across strategic cities in Albania, ensuring fast access and consistent service for every customer. Every liter of fuel we offer goes through strict control processes, in compliance with national and international standards.",
    about_who_p3: "For us, fuel is not just a product — it is a responsibility. Responsibility towards our customers, our partners, and the environment in which we operate.",
    about_page_kicker: "About us",
    about_page_title: "<span>Local energy that keeps</span><span>Albania moving.</span>",
    about_page_lead: "Micka Oil builds dependable supply for drivers, families, fleets, and businesses that need standards, pace, and long-term reliability.",
    about_page_cta_primary: "Contact us",
    about_page_cta_secondary: "View our network",
    about_page_badge_label: "On the ground every day",
    about_page_badge_title: "Stable supply, service with standards.",
    about_page_badge_text: "From urban stations to fleet supply, we keep the same focus: controlled quality and fast response.",
    about_metric_availability: "Service at key stations",
    about_metric_business: "Support for fleets and businesses",
    about_story_kicker: "Our story",
    about_story_title: "Micka Oil was built on reliability, not just volume.",
    about_story_p1: "From the beginning, our goal has been clear: build a supply network with discipline, transparency, and respect for the customer. For us, fuel is part of the daily rhythm of the people and businesses that trust us.",
    about_story_p2: "Micka Oil has grown by investing in strategic stations, quality control, and practical service for Albanian roads. That is what has made us a useful partner for individual drivers, companies, transport, and fleets.",
    about_manifesto_label: "For us",
    about_manifesto_text: "Fuel is not just a product. It is a responsibility toward our customers, our partners, and every road where our brand moves.",
    about_network_label: "Network on the ground",
    about_network_text: "Active presence in Tirana, Kavaje, Memaliaj, Patos, Gjirokaster, and Prush, focused on fast access and coverage of key areas.",
    about_pillars_kicker: "Why clients choose us",
    about_pillars_title: "What keeps clients close to Micka Oil",
    about_pillars_text: "Trust is built by how a company operates every day. These are the reasons our clients feel on the ground.",
    about_pillar1_title: "Controlled quality",
    about_pillar1_text: "Monitored products and consistent standards at every fueling point.",
    about_pillar2_title: "Network in key locations",
    about_pillar2_text: "Presence in cities and road axes that support the daily movement of our clients.",
    about_pillar3_title: "Business solutions",
    about_pillar3_text: "Support for companies, fleets, and volume supply based on real operational needs.",
    about_pillar4_title: "Continuous service",
    about_pillar4_text: "Steady operating rhythm, fast response, and focus on long-term relationships.",
    about_journey_kicker: "Journey and growth",
    about_journey_title: "From a local base to a network covering key points",
    about_journey_text: "Our growth has come through careful expansion, investment in standards, and closer alignment with the real needs of the Albanian market.",
    about_journey_2003_title: "Brand beginnings",
    about_journey_2003_text: "The first steps of Micka Oil with a focus on local supply and trusted client relationships.",
    about_journey_2008_title: "Network expansion",
    about_journey_2008_text: "Broader presence in strategic cities and stronger supply infrastructure.",
    about_journey_2015_title: "Entry into business supply",
    about_journey_2015_text: "Dedicated solutions for businesses, transport, and fleets with larger operational demands.",
    about_journey_2020_title: "Service modernization",
    about_journey_today_title: "Energy partner on the ground",
    about_journey_today_text: "An active network that combines product quality with pace, proximity, and dependable support.",
    about_cta_kicker: "Partnership",
    about_cta_title: "Ready for more dependable supply?",
    about_cta_text: "Contact our team for partnerships, business supply, and long-term solutions that move at your pace.",
    about_cta_button: "Contact us",
    stats_years: "Years of Experience",
    stats_stations: "Fuel Stations",
    stats_customers: "Satisfied Customers",
    stats_cities: "Cities in Albania",
    mission_title: "Our Mission",
    mission_text: "To provide safe, quality, and sustainable fuel supply, building long-term relationships with our customers and partners.",
    vision_title: "Our Vision",
    vision_text: "To be one of the most trusted energy companies in Albania, continuously expanding and investing in quality, technology, and people.",
    values_title: "Our Values",
    value1_title: "Quality",
    value1_desc: "— every product tested and certified",
    value2_title: "Reliability",
    value2_desc: "— integrity in every partnership",
    value3_title: "Transparency",
    value3_desc: "— open and honest communication",
    value4_title: "Partnership",
    value4_desc: "— we grow together with our customers",
    value5_title: "Responsibility",
    value5_desc: "— towards the environment and community",
    partners_title: "Our Partners",
    partners_text: "Micka Oil collaborates with reliable suppliers and partners to guarantee consistent quality and high service standards.",
    partner1: "Fuel Suppliers",
    partner2: "Businesses & Fleets",
    partner3: "Transport & Logistics",
    partner4: "Institutions & Projects",
    timeline_title: "Our Journey",
    timeline_2003: "Founding of Micka Oil with a focus on local supply and reliable service.",
    timeline_2008: "Expansion of the fuel station network and quality investments.",
    timeline_2015: "Beginning of partnerships with businesses, fleets, and various industries.",
    timeline_2020: "Modernization of services and standardization according to European practices.",
    timeline_today_year: "TODAY",
    timeline_today: "Micka Oil operates in several Albanian cities as a trusted energy partner.",
    cta_title: "Why Micka Oil?",
    cta_text: "Because we don't just sell fuel — we build trust.",
    cta_button: "Contact Us",
    
    // ========== LOYALTY CARDS PAGE ==========
    loyalty_hero_title: "LOYALTY CARD",
    loyalty_card1_title: "Loyalty Card",
    loyalty_card1_desc: "For personal use and benefits collection.",
    loyalty_card1_benefit1: "Personal use",
    loyalty_card1_benefit2: "Application is done at the station",
    loyalty_card1_benefit3: "Get 5 lekë below the board price",
    loyalty_card1_benefit4: "Specific to one vehicle",
    loyalty_card1_note: "ℹ️ Card is activated immediately at the supply station.",
    loyalty_card2_title: "VIP Card",
    loyalty_card2_desc: "Exclusive discounts and benefits.",
    loyalty_card2_benefit1: "Application valid for specific products we trade",
    loyalty_card2_benefit2: "Use is personal and realized with prepayment",
    loyalty_card2_benefit3: "Supply offered for any vehicle using the same product",
    loyalty_card2_benefit4: "Minimum quantity to qualify is 1000 liters",
    loyalty_card2_benefit5: "Terms and discounts are determined based on request",
    loyalty_card2_benefit6: "For additional details, contact our agent",
    loyalty_card2_note: "ℹ️ VIP benefits are activated according to agreement with Micka Oil.",
    loyalty_card3_title: "Fleet Card",
    loyalty_card3_desc: "Solution for businesses and fleets.",
    loyalty_card3_benefit1: "Electronic toll with prepayment or postpayment",
    loyalty_card3_benefit2: "Dedicated for businesses and companies",
    loyalty_card3_benefit3: "Valid for any registered vehicle",
    loyalty_card3_benefit4: "Discounts depend on consumption and demand",
    loyalty_card3_benefit5: "For more information, contact our agent",
    loyalty_card3_note: "ℹ️ Maximum flexibility for fleet management.",
    loyalty_btn_view: "View Benefits",
    loyalty_btn_close: "Close Benefits",
    loyalty_support_title: "Need help with your loyalty card?",
    loyalty_support_text: "Contact us for registration, points, balance, activation, or account support.",
    loyalty_support_button: "Ask about the card",
    loyalty_support_meta1: "For station assistance or urgent questions, our team is available 24/7.",
    loyalty_support_meta2: "Thank you for choosing Micka Oil. We keep your journey moving.",
    loyalty_page_title: "More than a card<br><span>loyalty that rewards you.</span>",
    loyalty_page_lead1: "Choose the card that fits your needs.",
    loyalty_page_lead2: "Get more value with every Micka Oil refuel.",
    loyalty_page_apply: "Apply now",
    loyalty_page_how: "How it works",
    loyalty_compare_title: "Compare benefits",
    loyalty_plan_standard: "Standard",
    loyalty_plan_vip: "VIP",
    loyalty_plan_business: "Business",
    loyalty_benefit_label: "Benefit",
    loyalty_benefit_use: "Use",
    loyalty_benefit_fuel: "Fuel discount",
    loyalty_benefit_offers: "Exclusive offers and promotions",
    loyalty_benefit_points: "Bonus point collection",
    loyalty_benefit_priority: "Service priority",
    loyalty_benefit_fleet: "Vehicle fleet management",
    loyalty_benefit_reports: "Monthly consumption reports",
    loyalty_benefit_invoice: "Invoice payment",
    loyalty_benefit_support: "Dedicated support",
    loyalty_value_2lek: "2 ALL/L",
    loyalty_value_5lek: "5 ALL/L",
    loyalty_value_7lek: "7 ALL/L",
    loyalty_value_personal: "Personal",
    loyalty_value_business_use: "Business",
    loyalty_steps_title: "How it works?",
    loyalty_step1_title: "Apply",
    loyalty_step1_text: "Fill out the form online or at our stations.",
    loyalty_step2_title: "Get the card",
    loyalty_step2_text: "Receive your physical card or digital format.",
    loyalty_step3_title: "Fuel and benefit",
    loyalty_step3_text: "Fuel at Micka Oil stations and benefit every day.",
    loyalty_reasons_title: "Why choose the Micka Oil loyalty card?",
    loyalty_reason1: "Fast registration<br>Apply easily online or at a station.",
    loyalty_reason2: "Valid across our full station network.",
    loyalty_reason3: "Exclusive offers and discounts throughout the year.",
    loyalty_reason4: "Dedicated support for every question and request.",
    loyalty_faq_title: "Frequently asked questions",
    loyalty_faq1_q: "Where can I use the loyalty card?",
    loyalty_faq1_a: "You can use the Micka Oil loyalty card at all participating stations. Simply present it during fueling to benefit from the loyalty program.",
    loyalty_faq2_q: "How are loyalty points collected?",
    loyalty_faq2_a: "Every time you fuel at Micka Oil, you collect loyalty points based on the value of your purchase. Points are registered automatically on your card and can be used for different benefits.",
    loyalty_faq3_q: "Is there a cost to get the card?",
    loyalty_faq3_a: "No. Applying for and receiving the loyalty card is completely free for all our customers.",
    loyalty_faq4_q: "What happens if I lose the card?",
    loyalty_faq4_a: "If the card is lost, contact the staff at the nearest Micka Oil station. The card can be deactivated and the accumulated benefits can be transferred to a new card.",
    loyalty_cta_title: "Ready to benefit?",
    loyalty_cta_text: "Join thousands of drivers who choose Micka Oil every day.",
    
    // ========== FOOTER ==========
    footer_brand_text: "Quality fuel, dependable service, and professional support at every station.",
    footer_menu: "Menu",
    footer_about: "About Us",
    footer_gallery: "Gallery",
    footer_locations: "Locations",
    footer_loyalty: "Loyalty Card",
    footer_contact: "Contact",
    footer_contact_title: "Contact",
    footer_follow: "Follow Us",
    footer_rights: "All rights reserved.",

    // ========== THANK YOU PAGE ==========
    thankyou_brand_tag: "Reliable supply",
    thankyou_side_title: "Your request was received.",
    thankyou_side_text: "Your message has been accepted by our system and will be reviewed by the relevant team.",
    thankyou_status_received: "Message received",
    thankyou_status_followup: "Team follow-up",
    thankyou_kicker: "Thank you",
    thankyou_title: "Your request was sent successfully.",
    thankyou_text: "Thank you for contacting Micka Oil. Our team will review the submitted details and contact you as soon as possible for the next steps.",
    thankyou_step1_title: "Request review",
    thankyou_step1_text: "The submitted information will be verified by the relevant team.",
    thankyou_step2_title: "Next contact",
    thankyou_step2_text: "We will contact you with a response, clarification, or partnership follow-up.",
    thankyou_home_cta: "Home page",
    thankyou_phone_cta: "Direct contact",
    thankyou_redirect: "You will be redirected automatically to the home page after 20 seconds."
  }
};

// =========================================================
// 02. LANGUAGE TOGGLE SETUP
// =========================================================

// Get current language from localStorage or default to 'sq'
let currentLang = localStorage.getItem('language') || 'sq';

// Apply language on page load
document.addEventListener('DOMContentLoaded', () => {
  const toggle = document.getElementById('langToggle');

  applyTranslations(currentLang);

  if (!toggle) return;

  // Set toggle state based on current language
  toggle.checked = currentLang === 'en';

  // Listen for toggle changes
  toggle.addEventListener('change', () => {
    currentLang = toggle.checked ? 'en' : 'sq';
    localStorage.setItem('language', currentLang);
    applyTranslations(currentLang);
  });
});

// =========================================================
// 03. DOM TRANSLATION RENDERER
// =========================================================
function applyTranslations(lang) {
  const dictionary = translations[lang] || translations.sq;
  const elements = document.querySelectorAll('[data-lang]');

  elements.forEach(el => {
    const key = el.getAttribute('data-lang');
    if (dictionary[key]) {
      el.textContent = dictionary[key];
    }
  });

  const htmlElements = document.querySelectorAll('[data-lang-html]');
  htmlElements.forEach(el => {
    const key = el.getAttribute('data-lang-html');
    if (dictionary[key]) {
      el.innerHTML = dictionary[key].replace(/\n/g, '<br>');
    }
  });

  const metaElements = document.querySelectorAll('[data-meta-lang]');
  metaElements.forEach(el => {
    const key = el.getAttribute('data-meta-lang');
    if (dictionary[key]) {
      el.setAttribute('content', dictionary[key]);
    }
  });

  document.documentElement.lang = lang === 'en' ? 'en' : 'sq';

  // Update loyalty card toggle buttons
  updateLoyaltyButtons(lang);

  if (typeof window.renderHomeFuelPrices === 'function') {
    window.renderHomeFuelPrices();
  }
}

// =========================================================
// 04. LOYALTY CARD BUTTON LABELS
// =========================================================
function updateLoyaltyButtons(lang) {
  const toggleButtons = document.querySelectorAll('.toggle-details');
  
  toggleButtons.forEach(btn => {
    const item = btn.closest('.loyalty-item');
    const details = item?.querySelector('.loyalty-details');
    const isOpen = details?.classList.contains('active');
    
    if (isOpen) {
      btn.textContent = translations[lang].loyalty_btn_close || 'Close Benefits';
    } else {
      btn.textContent = translations[lang].loyalty_btn_view || 'View Benefits';
    }
  });
}
